import { jsPDF } from 'jspdf';

/**
 * Section configuration for the diagnosis report.
 * Maps JSON keys to human-readable headings, in order.
 * @type {Array<{key: string, label: string}>}
 */
const SECTIONS = [
  { key: 'crop_identified', label: 'Crop Identified' },
  { key: 'disease_identified', label: 'Disease Identified' },
  { key: 'disease_overview', label: 'Disease Overview' },
  { key: 'symptoms', label: 'Symptoms' },
  { key: 'causes', label: 'Causes' },
  { key: 'severity', label: 'Severity' },
  { key: 'immediate_steps', label: 'Immediate Steps' },
  { key: 'treatment', label: 'Treatment' },
  { key: 'prevention', label: 'Prevention' },
  { key: 'possible_impact', label: 'Possible Impact' },
  { key: 'monitoring_advice', label: 'Monitoring Advice' },
];

/**
 * Generate and download a formatted PDF diagnosis report.
 *
 * @param {object} reportData - The structured report data (11 keys from LLM).
 * @param {string} cropName   - The identified crop name.
 * @param {string} diseaseName - The identified disease class label.
 */
export function generatePDF(reportData, cropName, diseaseName) {
  const doc = new jsPDF('p', 'mm', 'a4');

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 20;
  const marginRight = 20;
  const marginTop = 20;
  const marginBottom = 20;
  const contentWidth = pageWidth - marginLeft - marginRight;

  let y = marginTop;

  // ── Helper: check page overflow ──────────────────────────────────────
  /**
   * Ensure there is enough vertical space. If not, add a new page.
   * @param {number} needed - Required vertical space in mm.
   */
  const ensureSpace = (needed) => {
    if (y + needed > pageHeight - marginBottom) {
      doc.addPage();
      y = marginTop;
    }
  };

  // ── Header Block ─────────────────────────────────────────────────────
  const headerHeight = 22;
  doc.setFillColor(26, 92, 42); // #1a5c2a
  doc.rect(0, 0, pageWidth, headerHeight, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text('TerraMind', marginLeft, 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Smarter Farming Every Stage', marginLeft, 16);

  y = headerHeight + 8;

  // ── Date + Separator ─────────────────────────────────────────────────
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  }) + ', ' + now.toLocaleTimeString('en-GB', {
    hour: '2-digit',
    minute: '2-digit',
  });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(136, 136, 136); // gray
  doc.text(`Report generated: ${dateStr}`, pageWidth - marginRight, y, {
    align: 'right',
  });
  y += 4;

  // Thin horizontal rule
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 6;

  // ── Sections ─────────────────────────────────────────────────────────
  for (const section of SECTIONS) {
    const content = reportData[section.key] || 'N/A';

    // Section heading
    ensureSpace(14);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(26, 92, 42); // #1a5c2a
    doc.text(section.label, marginLeft, y);
    y += 1.5;

    // Sub-line under heading
    doc.setDrawColor(180, 180, 180);
    doc.setLineWidth(0.3);
    doc.line(marginLeft, y, pageWidth - marginRight, y);
    y += 5;

    // Section content
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(17, 17, 17); // #111111
    const lines = doc.splitTextToSize(content, contentWidth);

    for (let i = 0; i < lines.length; i++) {
      ensureSpace(5);
      doc.text(lines[i], marginLeft, y);
      y += 4.5;
    }

    y += 6; // 6pt spacing after section
  }

  // ── Footer on every page ─────────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(136, 136, 136); // #888888
    doc.text(
      'Generated by TerraMind | Confidential Agricultural Report',
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // ── Save / Download ──────────────────────────────────────────────────
  const safeCrop = (cropName || 'Unknown').replace(/\s+/g, '_');
  const safeDisease = (diseaseName || 'Unknown')
    .replace(/___/g, '_')
    .replace(/__/g, '_')
    .replace(/\s+/g, '_');
  const dateTag =
    now.getFullYear().toString() +
    String(now.getMonth() + 1).padStart(2, '0') +
    String(now.getDate()).padStart(2, '0');

  const filename = `TerraMind_Report_${safeCrop}_${safeDisease}_${dateTag}.pdf`;
  doc.save(filename);
}
