"""Static agricultural knowledge base for TerraMind Graph RAG."""

CROPS = {
    "cotton": {
        "name_en": "Cotton",
        "name_hi": "कपास",
        "scientific_name": "Gossypium hirsutum",
        "type": "kharif",
        "seasons": ["kharif"],
        "states": [
            "Gujarat", "Maharashtra", "Telangana", "Punjab", "Haryana",
            "Madhya Pradesh", "Rajasthan", "Karnataka",
        ],
        "growth_days": (150, 180),
        "soil_types": ["Black_Cotton_Soil", "Alluvial", "Red_Laterite"],
        "water_requirement": "moderate",
        "agrovoc_id": "c_1926",
    },
    "wheat": {
        "name_en": "Wheat",
        "name_hi": "गेहूं",
        "scientific_name": "Triticum aestivum",
        "type": "rabi",
        "seasons": ["rabi"],
        "states": ["Punjab", "Haryana", "Uttar Pradesh", "Madhya Pradesh", "Rajasthan", "Bihar"],
        "growth_days": (120, 150),
        "soil_types": ["Alluvial", "Clay_Loam", "Sandy_Loam"],
        "water_requirement": "moderate",
        "agrovoc_id": "c_8373",
    },
    "rice": {
        "name_en": "Rice",
        "name_hi": "धान",
        "scientific_name": "Oryza sativa",
        "type": "kharif",
        "seasons": ["kharif"],
        "states": [
            "West Bengal", "Uttar Pradesh", "Punjab", "Andhra Pradesh",
            "Telangana", "Tamil Nadu", "Odisha", "Bihar",
        ],
        "growth_days": (100, 150),
        "soil_types": ["Clay", "Clay_Loam", "Alluvial"],
        "water_requirement": "high",
        "agrovoc_id": "c_6599",
    },
    "tomato": {
        "name_en": "Tomato",
        "name_hi": "टमाटर",
        "scientific_name": "Solanum lycopersicum",
        "type": "vegetable",
        "seasons": ["rabi", "kharif", "zaid"],
        "states": ["Andhra Pradesh", "Karnataka", "Maharashtra", "Odisha", "West Bengal", "Madhya Pradesh"],
        "growth_days": (60, 90),
        "soil_types": ["Sandy_Loam", "Alluvial", "Red_Laterite"],
        "water_requirement": "moderate",
        "agrovoc_id": "c_7774",
    },
    "maize": {
        "name_en": "Maize",
        "name_hi": "मक्का",
        "scientific_name": "Zea mays",
        "type": "kharif",
        "seasons": ["kharif", "rabi"],
        "states": ["Karnataka", "Andhra Pradesh", "Tamil Nadu", "Maharashtra", "Bihar", "Uttar Pradesh"],
        "growth_days": (90, 120),
        "soil_types": ["Sandy_Loam", "Loam", "Alluvial"],
        "water_requirement": "moderate",
        "agrovoc_id": "c_4738",
    },
    "chickpea": {
        "name_en": "Chickpea",
        "name_hi": "चना",
        "scientific_name": "Cicer arietinum",
        "type": "rabi",
        "seasons": ["rabi"],
        "states": ["Madhya Pradesh", "Rajasthan", "Maharashtra", "Uttar Pradesh", "Andhra Pradesh", "Karnataka"],
        "growth_days": (90, 110),
        "soil_types": ["Sandy_Loam", "Loam", "Black_Cotton_Soil"],
        "water_requirement": "low",
        "agrovoc_id": "c_1544",
    },
    "potato": {
        "name_en": "Potato",
        "name_hi": "आलू",
        "scientific_name": "Solanum tuberosum",
        "type": "rabi",
        "seasons": ["rabi"],
        "states": ["Uttar Pradesh", "West Bengal", "Bihar", "Gujarat", "Punjab", "Madhya Pradesh"],
        "growth_days": (75, 120),
        "soil_types": ["Sandy_Loam", "Loam", "Alluvial"],
        "water_requirement": "moderate",
        "agrovoc_id": "c_6138",
    },
    "sugarcane": {
        "name_en": "Sugarcane",
        "name_hi": "गन्ना",
        "scientific_name": "Saccharum officinarum",
        "type": "perennial",
        "seasons": ["kharif"],
        "states": ["Uttar Pradesh", "Maharashtra", "Karnataka", "Tamil Nadu", "Andhra Pradesh", "Gujarat"],
        "growth_days": (270, 365),
        "soil_types": ["Alluvial", "Loam", "Black_Cotton_Soil"],
        "water_requirement": "high",
        "agrovoc_id": "c_7538",
    },
    "groundnut": {
        "name_en": "Groundnut",
        "name_hi": "मूंगफली",
        "scientific_name": "Arachis hypogaea",
        "type": "kharif",
        "seasons": ["kharif"],
        "states": ["Gujarat", "Andhra Pradesh", "Tamil Nadu", "Karnataka", "Maharashtra", "Madhya Pradesh"],
        "growth_days": (90, 130),
        "soil_types": ["Sandy_Loam", "Red_Laterite", "Loam"],
        "water_requirement": "moderate",
        "agrovoc_id": "c_4",
    },
    "mustard": {
        "name_en": "Mustard",
        "name_hi": "सरसों",
        "scientific_name": "Brassica juncea",
        "type": "rabi",
        "seasons": ["rabi"],
        "states": ["Rajasthan", "Uttar Pradesh", "Haryana", "Madhya Pradesh", "West Bengal", "Gujarat"],
        "growth_days": (90, 110),
        "soil_types": ["Sandy_Loam", "Loam", "Alluvial"],
        "water_requirement": "low",
        "agrovoc_id": "c_4944",
    },
}

PESTS = {
    "pink_bollworm": {
        "name_en": "Pink Bollworm",
        "name_hi": "गुलाबी सुंडी",
        "scientific_name": "Pectinophora gossypiella",
        "type": "insect",
        "order": "Lepidoptera",
        "damage_type": "borer",
        "affected_plant_parts": ["boll", "flower", "seed"],
        "economic_threshold": "10% infested bolls",
        "description": "Larvae bore into cotton bolls, causing internal damage and reducing fiber quality",
    },
    "whitefly": {
        "name_en": "Whitefly",
        "name_hi": "सफेद मक्खी",
        "scientific_name": "Bemisia tabaci",
        "type": "insect",
        "order": "Hemiptera",
        "damage_type": "sucking",
        "affected_plant_parts": ["leaf", "stem"],
        "economic_threshold": "10 adults per leaf",
        "description": "Sucks sap from leaves, excretes honeydew causing sooty mold, vectors leaf curl virus",
    },
    "aphid": {
        "name_en": "Aphid",
        "name_hi": "माहू / एफिड",
        "scientific_name": "Aphis gossypii",
        "type": "insect",
        "order": "Hemiptera",
        "damage_type": "sucking",
        "affected_plant_parts": ["leaf", "shoot", "stem"],
        "economic_threshold": "200-250 aphids per 100 leaves",
        "description": "Sucks sap, causes leaf curl and stunted growth, transmits mosaic virus",
    },
    "stem_borer": {
        "name_en": "Yellow Stem Borer",
        "name_hi": "पीला तना छेदक",
        "scientific_name": "Scirpophaga incertulas",
        "type": "insect",
        "order": "Lepidoptera",
        "damage_type": "borer",
        "affected_plant_parts": ["stem", "tiller"],
        "economic_threshold": "5% dead hearts or white ears",
        "description": "Larvae bore into rice stems causing dead heart in vegetative stage and white ear in reproductive stage",
    },
    "brown_planthopper": {
        "name_en": "Brown Planthopper",
        "name_hi": "भूरा फुदका",
        "scientific_name": "Nilaparvata lugens",
        "type": "insect",
        "order": "Hemiptera",
        "damage_type": "sucking",
        "affected_plant_parts": ["stem_base", "leaf"],
        "economic_threshold": "10 hoppers per hill",
        "description": "Sucks sap at base of plants, causes hopperburn (yellowing and drying)",
    },
    "fall_armyworm": {
        "name_en": "Fall Armyworm",
        "name_hi": "फॉल आर्मीवर्म",
        "scientific_name": "Spodoptera frugiperda",
        "type": "insect",
        "order": "Lepidoptera",
        "damage_type": "defoliator",
        "affected_plant_parts": ["leaf", "whorl", "ear"],
        "economic_threshold": "5% infested plants in whorl",
        "description": "Feeds on leaves and whorls of maize, can cause 20-70% yield loss if uncontrolled",
    },
    "pod_borer": {
        "name_en": "Gram Pod Borer",
        "name_hi": "फली छेदक",
        "scientific_name": "Helicoverpa armigera",
        "type": "insect",
        "order": "Lepidoptera",
        "damage_type": "borer",
        "affected_plant_parts": ["pod", "flower", "leaf"],
        "economic_threshold": "1-2 larvae per meter row",
        "description": "Highly polyphagous pest. Larvae feed on pods and grains, causes up to 50% yield loss in chickpea",
    },
    "late_blight_pathogen": {
        "name_en": "Late Blight (Potato)",
        "name_hi": "आलू का पछेता झुलसा",
        "scientific_name": "Phytophthora infestans",
        "type": "oomycete",
        "order": "Peronosporales",
        "damage_type": "foliar_blight",
        "affected_plant_parts": ["leaf", "stem", "tuber"],
        "economic_threshold": "First appearance = immediate action",
        "description": "Water mold causing rapid foliar blight, can destroy entire crop within 2 weeks in cool wet weather",
    },
    "thrips": {
        "name_en": "Thrips",
        "name_hi": "थ्रिप्स",
        "scientific_name": "Thrips tabaci",
        "type": "insect",
        "order": "Thysanoptera",
        "damage_type": "sucking",
        "affected_plant_parts": ["leaf", "flower"],
        "economic_threshold": "20 thrips per plant",
        "description": "Scrapes and sucks plant tissue, causes silvering of leaves, vectors tospoviruses",
    },
    "red_spider_mite": {
        "name_en": "Red Spider Mite",
        "name_hi": "लाल मकड़ी",
        "scientific_name": "Tetranychus urticae",
        "type": "mite",
        "order": "Trombidiformes",
        "damage_type": "sucking",
        "affected_plant_parts": ["leaf"],
        "economic_threshold": "5 mites per leaf",
        "description": "Feeds on underside of leaves, causes stippling and bronzing, thrives in hot dry conditions",
    },
    "leaf_folder": {
        "name_en": "Rice Leaf Folder",
        "name_hi": "चावल का पत्ता मोड़क",
        "scientific_name": "Cnaphalocrocis medinalis",
        "type": "insect",
        "order": "Lepidoptera",
        "damage_type": "defoliator",
        "affected_plant_parts": ["leaf"],
        "economic_threshold": "10% leaf damage",
        "description": "Larvae fold leaves longitudinally and feed inside, causing white streaks on leaves",
    },
    "sugarcane_pyrilla": {
        "name_en": "Sugarcane Pyrilla",
        "name_hi": "पायरिला",
        "scientific_name": "Pyrilla perpusilla",
        "type": "insect",
        "order": "Hemiptera",
        "damage_type": "sucking",
        "affected_plant_parts": ["leaf", "stem"],
        "economic_threshold": "10 hoppers per leaf",
        "description": "Major sugarcane pest, sucks sap and causes sooty mold through honeydew secretion",
    },
}

DISEASES = {
    "cotton_leaf_curl_virus": {
        "name_en": "Cotton Leaf Curl Virus",
        "name_hi": "कपास पत्ती मरोड़ रोग",
        "type": "viral",
        "pathogen": "Cotton leaf curl Multan virus",
        "vector": "whitefly",
        "symptoms": ["upward leaf curl", "thickening of veins", "stunted growth", "enations on underside"],
        "affected_parts": ["leaf", "stem"],
        "severity": "critical",
        "economic_impact": "up to 100% yield loss",
    },
    "early_blight_tomato": {
        "name_en": "Early Blight",
        "name_hi": "अगेती झुलसा",
        "type": "fungal",
        "pathogen": "Alternaria solani",
        "vector": None,
        "symptoms": ["dark brown spots with concentric rings", "yellowing around spots", "premature defoliation"],
        "affected_parts": ["leaf", "stem", "fruit"],
        "severity": "high",
        "economic_impact": "20-40% yield loss",
    },
    "blast_rice": {
        "name_en": "Rice Blast",
        "name_hi": "धान का ब्लास्ट",
        "type": "fungal",
        "pathogen": "Magnaporthe oryzae",
        "vector": None,
        "symptoms": ["diamond-shaped lesions on leaves", "neck rot", "panicle blast", "gray center with brown border"],
        "affected_parts": ["leaf", "neck", "panicle"],
        "severity": "critical",
        "economic_impact": "10-80% yield loss",
    },
    "powdery_mildew_wheat": {
        "name_en": "Powdery Mildew",
        "name_hi": "गेहूं का चूर्णिल आसिता",
        "type": "fungal",
        "pathogen": "Blumeria graminis f. sp. tritici",
        "vector": None,
        "symptoms": ["white powdery coating on leaves", "yellowing under coating", "reduced grain filling"],
        "affected_parts": ["leaf", "stem", "ear"],
        "severity": "medium",
        "economic_impact": "10-30% yield loss",
    },
    "late_blight_potato": {
        "name_en": "Late Blight",
        "name_hi": "आलू का पछेता झुलसा",
        "type": "oomycete",
        "pathogen": "Phytophthora infestans",
        "vector": None,
        "symptoms": ["dark water-soaked lesions", "white sporulation on underside", "rapid browning", "tuber rot"],
        "affected_parts": ["leaf", "stem", "tuber"],
        "severity": "critical",
        "economic_impact": "up to 100% yield loss",
    },
    "wilt_chickpea": {
        "name_en": "Fusarium Wilt",
        "name_hi": "चने का उखटा रोग",
        "type": "fungal",
        "pathogen": "Fusarium oxysporum f. sp. ciceri",
        "vector": None,
        "symptoms": ["sudden wilting", "yellowing from bottom", "browning of vascular tissue", "plant death"],
        "affected_parts": ["root", "stem", "vascular"],
        "severity": "high",
        "economic_impact": "10-90% yield loss",
    },
    "smut_sugarcane": {
        "name_en": "Sugarcane Smut",
        "name_hi": "गन्ने की कांगियारी",
        "type": "fungal",
        "pathogen": "Sporisorium scitamineum",
        "vector": None,
        "symptoms": ["whip-like black structure from top", "narrow grass-like leaves", "stunted tillers"],
        "affected_parts": ["shoot", "top"],
        "severity": "high",
        "economic_impact": "20-40% yield loss",
    },
    "tikka_groundnut": {
        "name_en": "Tikka Disease (Leaf Spot)",
        "name_hi": "मूंगफली का टिक्का रोग",
        "type": "fungal",
        "pathogen": "Cercospora arachidicola",
        "vector": None,
        "symptoms": ["circular dark brown spots", "yellow halo around spots", "premature defoliation"],
        "affected_parts": ["leaf"],
        "severity": "high",
        "economic_impact": "50-70% yield reduction if severe",
    },
}

PESTICIDES = {
    "chlorpyrifos": {"name_en": "Chlorpyrifos", "name_hi": "क्लोरपाइरीफॉस", "type": "insecticide", "chemical_class": "Organophosphate", "formulation": "EC 20%", "mode_of_action": "Cholinesterase inhibitor", "dose_range": (2.0, 2.5), "dose_unit": "ml/L", "application_method": "foliar_spray", "phi_days": 21, "max_applications": 2, "who_class": "II", "registered_india": True, "re_entry_hours": 24, "cost_per_liter_inr": 350},
    "spinosad": {"name_en": "Spinosad", "name_hi": "स्पिनोसैड", "type": "insecticide", "chemical_class": "Spinosyn (bio-based)", "formulation": "SC 45%", "mode_of_action": "Nicotinic receptor activator", "dose_range": (0.3, 0.5), "dose_unit": "ml/L", "application_method": "foliar_spray", "phi_days": 3, "max_applications": 3, "who_class": "U", "registered_india": True, "re_entry_hours": 4, "cost_per_liter_inr": 2200},
    "imidacloprid": {"name_en": "Imidacloprid", "name_hi": "इमिडाक्लोप्रिड", "type": "insecticide", "chemical_class": "Neonicotinoid", "formulation": "SL 17.8%", "mode_of_action": "Nicotinic acetylcholine receptor", "dose_range": (0.3, 0.5), "dose_unit": "ml/L", "application_method": "foliar_spray", "phi_days": 7, "max_applications": 2, "who_class": "II", "registered_india": True, "re_entry_hours": 12, "cost_per_liter_inr": 800},
    "mancozeb": {"name_en": "Mancozeb", "name_hi": "मैंकोज़ेब", "type": "fungicide", "chemical_class": "Dithiocarbamate", "formulation": "WP 75%", "mode_of_action": "Multi-site contact fungicide", "dose_range": (2.0, 2.5), "dose_unit": "g/L", "application_method": "foliar_spray", "phi_days": 15, "max_applications": 4, "who_class": "U", "registered_india": True, "re_entry_hours": 24, "cost_per_kg_inr": 280},
    "carbendazim": {"name_en": "Carbendazim", "name_hi": "कार्बेंडाज़िम", "type": "fungicide", "chemical_class": "Benzimidazole", "formulation": "WP 50%", "mode_of_action": "Tubulin synthesis inhibitor", "dose_range": (1.0, 1.5), "dose_unit": "g/L", "application_method": "foliar_spray", "phi_days": 10, "max_applications": 3, "who_class": "U", "registered_india": True, "re_entry_hours": 12, "cost_per_kg_inr": 400},
    "metalaxyl": {"name_en": "Metalaxyl", "name_hi": "मेटालैक्सिल", "type": "fungicide", "chemical_class": "Phenylamide", "formulation": "WP 35%", "mode_of_action": "RNA polymerase inhibitor", "dose_range": (2.0, 2.5), "dose_unit": "g/L", "application_method": "foliar_spray", "phi_days": 7, "max_applications": 2, "who_class": "III", "registered_india": True, "re_entry_hours": 12, "cost_per_kg_inr": 1200},
    "neem_oil": {"name_en": "Neem Oil", "name_hi": "नीम का तेल", "type": "biopesticide", "chemical_class": "Botanical", "formulation": "EC 1500ppm Azadirachtin", "mode_of_action": "IGR + antifeedant", "dose_range": (3.0, 5.0), "dose_unit": "ml/L", "application_method": "foliar_spray", "phi_days": 0, "max_applications": 5, "who_class": "U", "registered_india": True, "re_entry_hours": 0, "cost_per_liter_inr": 400},
    "thiamethoxam": {"name_en": "Thiamethoxam", "name_hi": "थायामेथोक्सम", "type": "insecticide", "chemical_class": "Neonicotinoid", "formulation": "WG 25%", "mode_of_action": "Nicotinic acetylcholine receptor", "dose_range": (0.2, 0.4), "dose_unit": "g/L", "application_method": "foliar_spray", "phi_days": 7, "max_applications": 2, "who_class": "III", "registered_india": True, "re_entry_hours": 12, "cost_per_kg_inr": 3500},
    "emamectin_benzoate": {"name_en": "Emamectin Benzoate", "name_hi": "एमामेक्टिन बेंजोएट", "type": "insecticide", "chemical_class": "Avermectin", "formulation": "SG 5%", "mode_of_action": "Glutamate-gated Cl channel", "dose_range": (0.2, 0.4), "dose_unit": "g/L", "application_method": "foliar_spray", "phi_days": 5, "max_applications": 3, "who_class": "III", "registered_india": True, "re_entry_hours": 12, "cost_per_kg_inr": 5000},
    "copper_oxychloride": {"name_en": "Copper Oxychloride", "name_hi": "कॉपर ऑक्सीक्लोराइड", "type": "fungicide", "chemical_class": "Inorganic copper", "formulation": "WP 50%", "mode_of_action": "Multi-site contact", "dose_range": (2.5, 3.0), "dose_unit": "g/L", "application_method": "foliar_spray", "phi_days": 14, "max_applications": 3, "who_class": "U", "registered_india": True, "re_entry_hours": 24, "cost_per_kg_inr": 250},
    "propiconazole": {"name_en": "Propiconazole", "name_hi": "प्रोपिकोनाजोल", "type": "fungicide", "chemical_class": "Triazole", "formulation": "EC 25%", "mode_of_action": "Ergosterol biosynthesis inhibitor", "dose_range": (1.0, 1.5), "dose_unit": "ml/L", "application_method": "foliar_spray", "phi_days": 14, "max_applications": 2, "who_class": "II", "registered_india": True, "re_entry_hours": 24, "cost_per_liter_inr": 700},
    "trichoderma": {"name_en": "Trichoderma viride", "name_hi": "ट्राइकोडर्मा", "type": "biofungicide", "chemical_class": "Biocontrol (fungal antagonist)", "formulation": "WP (2×10^6 CFU/g)", "mode_of_action": "Mycoparasitism + competition", "dose_range": (5.0, 10.0), "dose_unit": "g/L", "application_method": "soil_drench", "phi_days": 0, "max_applications": 3, "who_class": "U", "registered_india": True, "re_entry_hours": 0, "cost_per_kg_inr": 200},
}

SOIL_TYPES = {
    "Black_Cotton_Soil": {
        "name_en": "Black Cotton Soil (Vertisol)",
        "name_hi": "काली मिट्टी",
        "clay_content": "high",
        "drainage": "poor",
        "water_retention": "high",
        "pH_range": (7.5, 8.5),
        "organic_matter": "medium",
        "states": ["Maharashtra", "Madhya Pradesh", "Gujarat", "Telangana", "Karnataka"],
        "characteristics": ["shrinks when dry", "swells when wet", "waterlogging prone"],
    },
    "Alluvial": {
        "name_en": "Alluvial Soil",
        "name_hi": "जलोढ़ मिट्टी",
        "clay_content": "medium",
        "drainage": "good",
        "water_retention": "medium",
        "pH_range": (6.5, 7.5),
        "organic_matter": "high",
        "states": ["Punjab", "Haryana", "Uttar Pradesh", "Bihar", "West Bengal"],
        "characteristics": ["fertile", "well-drained", "suitable for most crops"],
    },
    "Sandy_Loam": {
        "name_en": "Sandy Loam",
        "name_hi": "बलुई दोमट मिट्टी",
        "clay_content": "low",
        "drainage": "very_good",
        "water_retention": "low",
        "pH_range": (6.0, 7.0),
        "organic_matter": "low",
        "states": ["Rajasthan", "Punjab", "Haryana", "Gujarat"],
        "characteristics": ["fast draining", "leaching prone", "good for root crops"],
    },
    "Red_Laterite": {
        "name_en": "Red Laterite Soil",
        "name_hi": "लाल लैटेराइट मिट्टी",
        "clay_content": "medium",
        "drainage": "good",
        "water_retention": "low",
        "pH_range": (5.5, 6.5),
        "organic_matter": "low",
        "states": ["Tamil Nadu", "Karnataka", "Andhra Pradesh", "Kerala", "Odisha"],
        "characteristics": ["acidic", "iron-rich", "low fertility"],
    },
    "Clay_Loam": {
        "name_en": "Clay Loam",
        "name_hi": "चिकनी दोमट मिट्टी",
        "clay_content": "medium-high",
        "drainage": "medium",
        "water_retention": "high",
        "pH_range": (6.5, 7.5),
        "organic_matter": "medium",
        "states": ["Madhya Pradesh", "Uttar Pradesh", "Chhattisgarh"],
        "characteristics": ["moderate fertility", "waterlogging risk", "good for wheat and paddy"],
    },
    "Loam": {
        "name_en": "Loam",
        "name_hi": "दोमट मिट्टी",
        "clay_content": "medium",
        "drainage": "good",
        "water_retention": "medium",
        "pH_range": (6.0, 7.0),
        "organic_matter": "medium-high",
        "states": ["Punjab", "Haryana", "Karnataka", "Andhra Pradesh"],
        "characteristics": ["balanced texture", "good aeration", "ideal for most crops"],
    },
}

CLIMATE_CONDITIONS = {
    "high_humidity": {"name_en": "High Humidity", "name_hi": "अधिक आर्द्रता", "threshold": "> 80% RH", "season_association": ["kharif", "monsoon"], "promotes": ["fungal diseases", "bacterial diseases", "aphid outbreaks", "mite suppression"]},
    "post_rain": {"name_en": "Post Heavy Rain", "name_hi": "भारी वर्षा के बाद", "threshold": "> 50mm rainfall in 24h", "season_association": ["kharif", "monsoon"], "promotes": ["waterlogging", "root diseases", "pest migration", "fungal sporulation"]},
    "dry_heat": {"name_en": "Dry Heat", "name_hi": "शुष्क गर्मी", "threshold": "> 35°C and < 40% RH", "season_association": ["zaid", "summer"], "promotes": ["spider mite outbreaks", "thrips activity", "wilting"]},
    "mild_temperature": {"name_en": "Mild Temperature", "name_hi": "सामान्य तापमान", "threshold": "20-28°C", "season_association": ["rabi"], "promotes": ["aphid buildup", "whitefly activity", "powdery mildew"]},
    "cool_wet": {"name_en": "Cool and Wet", "name_hi": "ठंडा और नम", "threshold": "< 20°C and > 70% RH", "season_association": ["rabi", "winter"], "promotes": ["late blight", "damping off", "grey mold", "Phytophthora"]},
    "high_temperature": {"name_en": "High Temperature", "name_hi": "अधिक तापमान", "threshold": "> 35°C", "season_association": ["zaid", "summer"], "promotes": ["bacterial diseases", "stem borer", "whitefly", "reduced disease incidence"]},
    "foggy": {"name_en": "Foggy / Overcast", "name_hi": "कोहरा / बादल", "threshold": "< 4 hrs sunshine/day", "season_association": ["rabi", "winter"], "promotes": ["powdery mildew", "rust", "aphid buildup", "leaf spot"]},
}

RELATIONSHIPS = {
    "crop_pest": [
        {"crop": "cotton", "pest": "pink_bollworm", "severity": "critical", "growth_stage": ["boll_development", "flowering"], "season": "kharif", "notes": "Primary pest of cotton in India"},
        {"crop": "cotton", "pest": "whitefly", "severity": "high", "growth_stage": ["vegetative", "flowering"], "season": "kharif", "notes": "Vector of cotton leaf curl virus"},
        {"crop": "cotton", "pest": "aphid", "severity": "medium", "growth_stage": ["vegetative", "early_flowering"], "season": "kharif", "notes": "Mosaic virus vector, population explodes post-rain"},
        {"crop": "cotton", "pest": "thrips", "severity": "medium", "growth_stage": ["seedling", "vegetative"], "season": "kharif"},
        {"crop": "cotton", "pest": "red_spider_mite", "severity": "high", "growth_stage": ["vegetative", "boll_development"], "season": "kharif", "notes": "Severe in dry hot weather"},
        {"crop": "rice", "pest": "stem_borer", "severity": "critical", "growth_stage": ["vegetative", "reproductive"], "season": "kharif", "notes": "Dead heart in vegetative, white ear in reproductive"},
        {"crop": "rice", "pest": "brown_planthopper", "severity": "critical", "growth_stage": ["vegetative", "reproductive"], "season": "kharif", "notes": "Hopperburn can destroy entire field"},
        {"crop": "rice", "pest": "leaf_folder", "severity": "medium", "growth_stage": ["vegetative"], "season": "kharif"},
        {"crop": "maize", "pest": "fall_armyworm", "severity": "critical", "growth_stage": ["vegetative", "whorl"], "season": "kharif", "notes": "Invasive pest, rapid spread, resistant strains emerging"},
        {"crop": "maize", "pest": "aphid", "severity": "medium", "growth_stage": ["vegetative"], "season": "kharif"},
        {"crop": "tomato", "pest": "whitefly", "severity": "high", "growth_stage": ["vegetative", "flowering"], "season": "all", "notes": "Tospoviruses vector"},
        {"crop": "tomato", "pest": "thrips", "severity": "high", "growth_stage": ["flowering"], "season": "all", "notes": "TSWV vector"},
        {"crop": "tomato", "pest": "pod_borer", "severity": "high", "growth_stage": ["fruiting"], "season": "kharif", "notes": "Attacks fruit directly"},
        {"crop": "chickpea", "pest": "pod_borer", "severity": "critical", "growth_stage": ["flowering", "pod_development"], "season": "rabi", "notes": "Most destructive pest of chickpea in India"},
        {"crop": "chickpea", "pest": "aphid", "severity": "medium", "growth_stage": ["vegetative", "flowering"], "season": "rabi"},
        {"crop": "sugarcane", "pest": "sugarcane_pyrilla", "severity": "high", "growth_stage": ["grand_growth"], "season": "kharif"},
        {"crop": "potato", "pest": "late_blight_pathogen", "severity": "critical", "growth_stage": ["tuber_initiation", "bulking"], "season": "rabi", "notes": "Cool wet conditions trigger explosive spread"},
        {"crop": "potato", "pest": "aphid", "severity": "medium", "growth_stage": ["vegetative"], "season": "rabi"},
        {"crop": "wheat", "pest": "aphid", "severity": "high", "growth_stage": ["boot", "heading"], "season": "rabi", "notes": "BYDV virus vector"},
        {"crop": "groundnut", "pest": "thrips", "severity": "medium", "growth_stage": ["vegetative", "flowering"], "season": "kharif"},
        {"crop": "groundnut", "pest": "red_spider_mite", "severity": "medium", "growth_stage": ["vegetative"], "season": "kharif"},
        {"crop": "mustard", "pest": "aphid", "severity": "critical", "growth_stage": ["flowering", "pod_filling"], "season": "rabi", "notes": "Mustard aphid (Lipaphis erysimi) - devastating"},
    ],
    "crop_disease": [
        {"crop": "cotton", "disease": "cotton_leaf_curl_virus", "severity": "critical", "season": "kharif", "notes": "No chemical cure, only prevention via vector control"},
        {"crop": "tomato", "disease": "early_blight_tomato", "severity": "high", "season": "all", "notes": "Favored by alternating wet-dry conditions"},
        {"crop": "rice", "disease": "blast_rice", "severity": "critical", "season": "kharif", "notes": "Neck blast at panicle emergence = complete yield loss"},
        {"crop": "wheat", "disease": "powdery_mildew_wheat", "severity": "medium", "season": "rabi", "notes": "Foggy winters favor rapid spread"},
        {"crop": "potato", "disease": "late_blight_potato", "severity": "critical", "season": "rabi", "notes": "Cool wet nights trigger epidemic"},
        {"crop": "chickpea", "disease": "wilt_chickpea", "severity": "high", "season": "rabi", "notes": "Soil-borne, persists for years"},
        {"crop": "sugarcane", "disease": "smut_sugarcane", "severity": "high", "season": "kharif", "notes": "Use disease-free setts only"},
        {"crop": "groundnut", "disease": "tikka_groundnut", "severity": "high", "season": "kharif", "notes": "Late season defoliation severely impacts yield"},
    ],
    "disease_treatment": [
        {"disease": "early_blight_tomato", "pesticide": "mancozeb", "efficacy": "high", "timing": "preventive", "spray_interval_days": 7, "notes": "Start at first sign of disease"},
        {"disease": "early_blight_tomato", "pesticide": "copper_oxychloride", "efficacy": "medium", "timing": "preventive", "spray_interval_days": 10},
        {"disease": "early_blight_tomato", "pesticide": "propiconazole", "efficacy": "high", "timing": "curative", "spray_interval_days": 14, "notes": "Use when disease is already established"},
        {"disease": "blast_rice", "pesticide": "carbendazim", "efficacy": "high", "timing": "curative", "spray_interval_days": 10, "notes": "Apply at boot leaf and panicle emergence"},
        {"disease": "blast_rice", "pesticide": "propiconazole", "efficacy": "high", "timing": "both", "spray_interval_days": 14},
        {"disease": "powdery_mildew_wheat", "pesticide": "propiconazole", "efficacy": "high", "timing": "curative", "spray_interval_days": 14},
        {"disease": "powdery_mildew_wheat", "pesticide": "carbendazim", "efficacy": "medium", "timing": "preventive", "spray_interval_days": 10},
        {"disease": "late_blight_potato", "pesticide": "metalaxyl", "efficacy": "high", "timing": "both", "spray_interval_days": 7, "notes": "Best systemic option for late blight"},
        {"disease": "late_blight_potato", "pesticide": "mancozeb", "efficacy": "medium", "timing": "preventive", "spray_interval_days": 7},
        {"disease": "late_blight_potato", "pesticide": "copper_oxychloride", "efficacy": "medium", "timing": "preventive", "spray_interval_days": 10},
        {"disease": "wilt_chickpea", "pesticide": "trichoderma", "efficacy": "medium", "timing": "preventive", "application": "seed_treatment_and_soil_drench", "notes": "Biological control, use at sowing"},
        {"disease": "tikka_groundnut", "pesticide": "mancozeb", "efficacy": "high", "timing": "preventive", "spray_interval_days": 10},
        {"disease": "tikka_groundnut", "pesticide": "carbendazim", "efficacy": "high", "timing": "both", "spray_interval_days": 14},
        {"disease": "smut_sugarcane", "pesticide": "carbendazim", "efficacy": "medium", "timing": "preventive", "application": "sett_treatment", "notes": "Soak setts before planting"},
    ],
    "pest_treatment": [
        {"pest": "pink_bollworm", "pesticide": "chlorpyrifos", "efficacy": "high", "timing": "curative", "notes": "Apply at economic threshold crossing"},
        {"pest": "pink_bollworm", "pesticide": "spinosad", "efficacy": "high", "timing": "curative", "notes": "Preferred - lower toxicity, WHO Class U"},
        {"pest": "pink_bollworm", "pesticide": "emamectin_benzoate", "efficacy": "high", "timing": "curative"},
        {"pest": "whitefly", "pesticide": "imidacloprid", "efficacy": "high", "timing": "curative", "notes": "Systemic - good for sucking pests"},
        {"pest": "whitefly", "pesticide": "thiamethoxam", "efficacy": "high", "timing": "curative"},
        {"pest": "whitefly", "pesticide": "neem_oil", "efficacy": "medium", "timing": "preventive", "notes": "Use early, repels whitefly and disrupts feeding"},
        {"pest": "aphid", "pesticide": "thiamethoxam", "efficacy": "high", "timing": "curative"},
        {"pest": "aphid", "pesticide": "imidacloprid", "efficacy": "high", "timing": "curative"},
        {"pest": "aphid", "pesticide": "neem_oil", "efficacy": "medium", "timing": "preventive"},
        {"pest": "stem_borer", "pesticide": "chlorpyrifos", "efficacy": "high", "timing": "curative", "notes": "Target early instar larvae in leaf sheath"},
        {"pest": "stem_borer", "pesticide": "emamectin_benzoate", "efficacy": "high", "timing": "curative"},
        {"pest": "brown_planthopper", "pesticide": "chlorpyrifos", "efficacy": "high", "timing": "curative", "notes": "Drench at base of plants"},
        {"pest": "brown_planthopper", "pesticide": "thiamethoxam", "efficacy": "high", "timing": "curative"},
        {"pest": "fall_armyworm", "pesticide": "spinosad", "efficacy": "high", "timing": "curative", "notes": "Apply into whorl for best contact"},
        {"pest": "fall_armyworm", "pesticide": "emamectin_benzoate", "efficacy": "high", "timing": "curative"},
        {"pest": "fall_armyworm", "pesticide": "chlorpyrifos", "efficacy": "medium", "timing": "curative"},
        {"pest": "pod_borer", "pesticide": "emamectin_benzoate", "efficacy": "high", "timing": "curative", "notes": "Apply at flowering start"},
        {"pest": "pod_borer", "pesticide": "spinosad", "efficacy": "high", "timing": "curative"},
        {"pest": "thrips", "pesticide": "spinosad", "efficacy": "high", "timing": "curative"},
        {"pest": "thrips", "pesticide": "thiamethoxam", "efficacy": "high", "timing": "curative"},
        {"pest": "red_spider_mite", "pesticide": "neem_oil", "efficacy": "medium", "timing": "both", "notes": "Spray under leaf surface. Repeat every 5 days."},
        {"pest": "red_spider_mite", "pesticide": "chlorpyrifos", "efficacy": "low", "timing": "curative", "notes": "Not recommended as primary — mites can be resistant"},
        {"pest": "leaf_folder", "pesticide": "chlorpyrifos", "efficacy": "high", "timing": "curative"},
        {"pest": "leaf_folder", "pesticide": "spinosad", "efficacy": "high", "timing": "curative"},
        {"pest": "sugarcane_pyrilla", "pesticide": "chlorpyrifos", "efficacy": "high", "timing": "curative"},
        {"pest": "late_blight_pathogen", "pesticide": "metalaxyl", "efficacy": "high", "timing": "both"},
        {"pest": "late_blight_pathogen", "pesticide": "copper_oxychloride", "efficacy": "medium", "timing": "preventive"},
    ],
    "pesticide_soil_conflict": [
        {"pesticide": "chlorpyrifos", "soil": "Sandy_Loam", "conflict_type": "leaching", "severity": "high", "reason": "Rapid leaching through sandy profile, groundwater contamination risk, reduced efficacy", "recommendation": "Use emamectin_benzoate or spinosad instead"},
        {"pesticide": "chlorpyrifos", "soil": "Red_Laterite", "conflict_type": "degradation", "severity": "medium", "reason": "Acidic pH accelerates hydrolysis, reducing residual efficacy", "recommendation": "Increase frequency slightly or switch to spinosad"},
        {"pesticide": "metalaxyl", "soil": "Black_Cotton_Soil", "conflict_type": "accumulation", "severity": "medium", "reason": "Poor drainage causes accumulation, risk of phytotoxicity and residue buildup", "recommendation": "Use copper_oxychloride as alternative in poorly drained fields"},
        {"pesticide": "imidacloprid", "soil": "Sandy_Loam", "conflict_type": "leaching", "severity": "high", "reason": "Highly mobile in sandy soils, groundwater contamination risk, pollinator toxicity concern", "recommendation": "Use neem_oil or spinosad in sandy soils"},
        {"pesticide": "carbendazim", "soil": "Red_Laterite", "conflict_type": "inactivation", "severity": "medium", "reason": "Strongly adsorbed to acidic laterite, reduces bioavailability", "recommendation": "Use propiconazole in laterite soils"},
        {"pesticide": "trichoderma", "soil": "Red_Laterite", "conflict_type": "survival", "severity": "low", "reason": "Low pH reduces Trichoderma colonization", "recommendation": "Apply lime before Trichoderma application to raise pH"},
        {"pesticide": "copper_oxychloride", "soil": "Red_Laterite", "conflict_type": "accumulation", "severity": "medium", "reason": "Copper accumulates in acidic soils, risk of phytotoxicity over time", "recommendation": "Limit to 2 applications/season in laterite soils"},
        {"pesticide": "thiamethoxam", "soil": "Sandy_Loam", "conflict_type": "leaching", "severity": "high", "reason": "Highly water soluble, leaches rapidly in sandy profiles", "recommendation": "Use granular formulation or switch to emamectin_benzoate"},
    ],
    "pest_climate": [
        {"pest": "pink_bollworm", "climate": "high_humidity", "effect": "population_explosion", "mechanism": "High humidity increases moth activity and egg hatching rate", "risk_multiplier": 2.5},
        {"pest": "pink_bollworm", "climate": "post_rain", "effect": "migration_and_spread", "mechanism": "Rain triggers adult moth flight and redistribution across fields", "risk_multiplier": 2.0},
        {"pest": "whitefly", "climate": "dry_heat", "effect": "population_explosion", "mechanism": "Warm dry conditions favor rapid generation cycling (8-10 days/gen)", "risk_multiplier": 3.0},
        {"pest": "whitefly", "climate": "high_humidity", "effect": "moderate_increase", "mechanism": "High humidity supports but does not maximize whitefly populations", "risk_multiplier": 1.5},
        {"pest": "aphid", "climate": "mild_temperature", "effect": "population_explosion", "mechanism": "Optimal temperature (18-25°C) for asexual reproduction, rapid buildup", "risk_multiplier": 3.5},
        {"pest": "aphid", "climate": "post_rain", "effect": "moderate_increase", "mechanism": "Post-rain flush of new growth provides ideal feeding sites", "risk_multiplier": 1.8},
        {"pest": "aphid", "climate": "foggy", "effect": "population_explosion", "mechanism": "Overcast conditions suppress natural enemies, aphid populations surge", "risk_multiplier": 2.5},
        {"pest": "stem_borer", "climate": "high_humidity", "effect": "high_activity", "mechanism": "High humidity favors egg hatching and larval survival in leaf sheaths", "risk_multiplier": 2.0},
        {"pest": "brown_planthopper", "climate": "high_humidity", "effect": "population_explosion", "mechanism": "Continuous high humidity enables 3-4 generations per season", "risk_multiplier": 4.0},
        {"pest": "brown_planthopper", "climate": "post_rain", "effect": "high_activity", "mechanism": "Standing water and dense canopy after rain create ideal microclimate", "risk_multiplier": 2.5},
        {"pest": "fall_armyworm", "climate": "post_rain", "effect": "moderate_increase", "mechanism": "Post-rain green flush triggers adult oviposition", "risk_multiplier": 1.8},
        {"pest": "fall_armyworm", "climate": "high_humidity", "effect": "moderate_increase", "mechanism": "Humid conditions favor larval development in whorls", "risk_multiplier": 1.5},
        {"pest": "pod_borer", "climate": "mild_temperature", "effect": "high_activity", "mechanism": "Optimal flight and oviposition at 25-28°C", "risk_multiplier": 2.8},
        {"pest": "red_spider_mite", "climate": "dry_heat", "effect": "population_explosion", "mechanism": "Hot dry conditions reduce natural enemies and accelerate mite reproduction", "risk_multiplier": 5.0},
        {"pest": "late_blight_pathogen", "climate": "cool_wet", "effect": "epidemic_risk", "mechanism": "Cool nights + wet leaves = perfect sporulation conditions for Phytophthora", "risk_multiplier": 8.0},
        {"pest": "thrips", "climate": "dry_heat", "effect": "high_activity", "mechanism": "Dry conditions favor thrips, natural control reduced", "risk_multiplier": 2.5},
        {"pest": "leaf_folder", "climate": "high_humidity", "effect": "high_activity", "mechanism": "High humidity favors moth activity and larval survival", "risk_multiplier": 2.0},
        {"pest": "sugarcane_pyrilla", "climate": "high_humidity", "effect": "population_explosion", "mechanism": "Humid conditions favor nymphal survival and population buildup", "risk_multiplier": 2.5},
    ],
    "tank_mix_conflicts": [
        {"pesticide_a": "mancozeb", "pesticide_b": "copper_oxychloride", "reason": "Both are contact fungicides with copper components — combined phytotoxicity risk", "severity": "high"},
        {"pesticide_a": "carbendazim", "pesticide_b": "copper_oxychloride", "reason": "Copper inactivates carbendazim — renders carbendazim ineffective", "severity": "critical"},
        {"pesticide_a": "imidacloprid", "pesticide_b": "thiamethoxam", "reason": "Same mode of action (neonicotinoids) — no additive benefit, resistance risk", "severity": "medium"},
        {"pesticide_a": "chlorpyrifos", "pesticide_b": "propiconazole", "reason": "Chemical incompatibility, may cause emulsion breakdown and reduced efficacy", "severity": "medium"},
        {"pesticide_a": "neem_oil", "pesticide_b": "copper_oxychloride", "reason": "Copper denatures neem oil proteins, causes phytotoxicity", "severity": "high"},
        {"pesticide_a": "trichoderma", "pesticide_b": "carbendazim", "reason": "Carbendazim kills Trichoderma — completely negates biocontrol", "severity": "critical"},
        {"pesticide_a": "trichoderma", "pesticide_b": "copper_oxychloride", "reason": "Copper is toxic to Trichoderma spores", "severity": "critical"},
    ],
    "disease_climate": [
        {"disease": "early_blight_tomato", "climate": "high_humidity", "effect": "rapid_spread", "mechanism": "Humid conditions favor Alternaria sporulation and infection", "risk_multiplier": 3.0},
        {"disease": "blast_rice", "climate": "high_humidity", "effect": "epidemic", "mechanism": "Humid nights with leaf wetness favor Magnaporthe sporulation", "risk_multiplier": 4.0},
        {"disease": "late_blight_potato", "climate": "cool_wet", "effect": "explosive_spread", "mechanism": "Cool wet nights = perfect conditions for Phytophthora sporangia production", "risk_multiplier": 8.0},
        {"disease": "powdery_mildew_wheat", "climate": "foggy", "effect": "rapid_spread", "mechanism": "Overcast foggy conditions and mild temperature favor Blumeria germination", "risk_multiplier": 3.5},
        {"disease": "cotton_leaf_curl_virus", "climate": "high_humidity", "effect": "indirect_increase", "mechanism": "High humidity increases whitefly populations, which spread the virus", "risk_multiplier": 2.0},
        {"disease": "tikka_groundnut", "climate": "high_humidity", "effect": "rapid_spread", "mechanism": "Humid conditions favor Cercospora spore germination", "risk_multiplier": 3.0},
    ],
}
